### ISSUE TITLE
[MySQL-Sync] No valid MySQL Credentials is set in Config!

### ISSUE THREAD

**Issue by AndrewMiliy** [SphinxHD/MySQL-Sync#10]
i have this message when start server.
the credentials are definitely correct

```
[12:06:14 INFO]: [MySQL-Sync] Enabling MySQL-Sync v1.4.9
[12:06:14 ERROR]: [MySQL-Sync] No valid MySQL Credentials is set in Config!
 Disabling Plugin!
[12:06:14 INFO]: [MySQL-Sync] Disabling MySQL-Sync v1.4.9
[12:06:14 ERROR]: Error occurred (in the plugin loader) while disabling MySQL-Sync v1.4.9 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "hd.sphinx.sync.backup.BackupHandler.id" is null
	at hd.sphinx.sync.backup.BackupHandler.shutdown(BackupHandler.java:83) ~[MySQL-Sync-1.4.9.jar:?]
	at hd.sphinx.sync.MainManageData.startShutdown(MainManageData.java:88) ~[MySQL-Sync-1.4.9.jar:?]
	at hd.sphinx.sync.Main.onDisable(Main.java:78) ~[MySQL-Sync-1.4.9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-43]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at hd.sphinx.sync.mysql.MySQL.connectMySQL(MySQL.java:26) ~[MySQL-Sync-1.4.9.jar:?]
	at hd.sphinx.sync.MainManageData.initialize(MainManageData.java:38) ~[MySQL-Sync-1.4.9.jar:?]
	at hd.sphinx.sync.Main.onEnable(Main.java:62) ~[MySQL-Sync-1.4.9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-43]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:06:14 ERROR]: Error occurred while enabling MySQL-Sync v1.4.9 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "hd.sphinx.sync.mysql.MySQL.connection" is null
	at hd.sphinx.sync.mysql.MySQL.registerMySQL(MySQL.java:45) ~[MySQL-Sync-1.4.9.jar:?]
	at hd.sphinx.sync.MainManageData.initialize(MainManageData.java:40) ~[MySQL-Sync-1.4.9.jar:?]
	at hd.sphinx.sync.Main.onEnable(Main.java:62) ~[MySQL-Sync-1.4.9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-43]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by GesundesWasser** [comment]
Have The Same Issue

**Comment by SphinxHD** [comment]
Hello there,

just had some time to read all Bug reports, and now had some time for your error.
MySQL has a problem, with users, that don't have a password, so fix it for the long run, just give the user with which the Plugin connects to the database an password. If this is not the fix, please message me again. I will let this bug report open, till I hear from you back.

~ Leo
