### ISSUE TITLE
Error Report: Potion Effect Addition Failure Upon Player Inventory Load

### ISSUE THREAD

**Issue by MCE-MatchaMC** [SphinxHD/MySQL-Sync#17]
*Version Information:
```
Server Version: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
Plugin Version: MySQL-Sync-1.4.11
```

*Error Reproduction:
```
The error occurs when a player enters the server and their inventory is loaded.
```

*Error Log:
```
[18:19:25] [User Authenticator #0/INFO]: UUID of player YT_MatchaPudding is 0b060150-ad14-406d-bd47-58a5a8589fac
[18:19:26] [Region Scheduler Thread #0/INFO]: YT_MatchaPudding[/10.10.10.200:52666] logged in with entity id 329 at ([world]-2370.8059619624923, 180.0, 1110.9628257185009)
[18:19:26] [Region Scheduler Thread #0/INFO]: [CMI] CMI proxy plugin detected
[18:19:27] [Region Scheduler Thread #0/INFO]: [CMI] CMI detected Velocity network
[18:19:28] [Folia Async Scheduler Thread Timer/ERROR]: Thread Folia Async Scheduler Thread Timer failed main thread check: effect add
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:512) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:507) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:521) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
	at hd.sphinx.sync.mysql.ManageMySQLData.loadPlayer(ManageMySQLData.java:128) ~[MySQL-Sync-1.4.11.jar:?]
	at hd.sphinx.sync.MainManageData.loadPlayer(MainManageData.java:127) ~[MySQL-Sync-1.4.11.jar:?]
	at hd.sphinx.sync.util.scheduler.FoliaScheduler.lambda$scheduleJoin$1(FoliaScheduler.java:48) ~[MySQL-Sync-1.4.11.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by SphinxHD** [comment]
Hello there,

this Bug was fixed in the 1.4.13, you can find the latest version on [Spigot](https://www.spigotmc.org/resources/mysql-sync.101554/update?update=543166).

~ Leo
