### ISSUE TITLE
Error Encountered After Player Inventory Loading

### ISSUE THREAD

**Issue by MCE-MatchaMC** [SphinxHD/MySQL-Sync#18]
*Version Information:
```
Server Version: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
Plugin Version: MySQL-Sync-1.4.13
```

*Error Reproduction:
```
The error occurs after the player enters the server and their inventory is loaded.
```

*Error Log:
```
[20:55:52 INFO]: UUID of player YT_MatchaPudding is 0b060150-ad14-406d-bd47-58a5a8589fac
[20:55:53 INFO]: YT_MatchaPudding[/10.10.10.200:49212] logged in with entity id 330 at ([world]-2372.443091166627, 180.0, 1100.1668179666501)
[20:55:53 INFO]: [CMI] CMI proxy plugin detected
[20:55:54 INFO]: [CMI] CMI detected Velocity network
[20:55:55 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1170) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1165) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1156) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:513) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:507) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:521) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at hd.sphinx.sync.mysql.ManageMySQLData.loadPlayer(ManageMySQLData.java:129) ~[MySQL-Sync-1.4.13.jar:?]
        at hd.sphinx.sync.MainManageData.loadPlayer(MainManageData.java:127) ~[MySQL-Sync-1.4.13.jar:?]
        at hd.sphinx.sync.util.scheduler.FoliaScheduler.lambda$scheduleJoin$1(FoliaScheduler.java:48) ~[MySQL-Sync-1.4.13.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by MCE-MatchaMC** [comment]
The errors vanished inexplicably
