### ISSUE TITLE
Effects do not sync

### ISSUE THREAD

**Issue by Hezkore** [SphinxHD/MySQL-Sync#22]
```
logged in with entity id 76 at ([world]0.6382307527719131, 65.11607409325677, 0.10669720120495517)
[21:00:23 ERROR]: Thread Craft Scheduler Thread - 4 - MySQL-Sync failed main thread check: effect add
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:527) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:522) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:536) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at mysql-sync.jar/hd.sphinx.sync.mysql.ManageMySQLData.loadPlayer(ManageMySQLData.java:128) ~[mysql-sync.jar:?]
        at mysql-sync.jar/hd.sphinx.sync.MainManageData.loadPlayer(MainManageData.java:127) ~[mysql-sync.jar:?]
        at mysql-sync.jar/hd.sphinx.sync.util.scheduler.SpigotScheduler$2.run(SpigotScheduler.java:40) ~[mysql-sync.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by SphinxHD** [comment]
Hello Hezkore,

can you give me more Informations to this bug? (Server Version, Server Software and Plugin Version)
This would help to fix this problem ASAP

~ Leo

**Comment by Hezkore** [comment]
I don't have the exact details right now.
But it's the latest PaperMC, Minecraft and plugin version as of 2024-09-11.

**Comment by SphinxHD** [comment]
Thank you, this will help greatly. I will message you soon.
